name: Local Config
version: 1.0.0
schema: v1

models:
  - uses: openai/gpt-4o-mini
    with:
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}

  - uses: openai/gpt-4.1-mini
    with:
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
